//
// DeviceTypeInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public class DeviceTypeInfo: JSONEncodable {
    /** Device Properties Enabled */
    public var devicePropertiesEnabled: Bool?
    /** Pmax value */
    public var pmax: Int32?
    /** Modified on */
    public var modifiedOn: Int64?
    /** Device Type ID */
    public var dtid: String?
    /** Pmin value */
    public var pmin: Int32?
    /** Default task expiration time in seconds */
    public var taskExpiresAfter: Int32?
    /** Created on */
    public var createdOn: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["devicePropertiesEnabled"] = self.devicePropertiesEnabled
        nillableDictionary["pmax"] = self.pmax?.encodeToJSON()
        nillableDictionary["modifiedOn"] = self.modifiedOn?.encodeToJSON()
        nillableDictionary["dtid"] = self.dtid
        nillableDictionary["pmin"] = self.pmin?.encodeToJSON()
        nillableDictionary["taskExpiresAfter"] = self.taskExpiresAfter?.encodeToJSON()
        nillableDictionary["createdOn"] = self.createdOn?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
