//
// MetadataQueryEnvelope.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public class MetadataQueryEnvelope: JSONEncodable {
    /** Number of results found */
    public var total: Int32?
    /** Array of objects with device&#39;s metadata */
    public var data: [String:AnyObject]?
    /** Page starting position */
    public var offset: Int32?
    /** Page size */
    public var count: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["total"] = self.total?.encodeToJSON()
        nillableDictionary["data"] = self.data?.encodeToJSON()
        nillableDictionary["offset"] = self.offset?.encodeToJSON()
        nillableDictionary["count"] = self.count?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
