//
// TaskRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public class TaskRequest: JSONEncodable {
    /** Filter */
    public var filter: String?
    /** Task type */
    public var taskType: String?
    /** Device Type ID */
    public var dtid: String?
    /** Property */
    public var property: String?
    /** Device IDs */
    public var dids: [String]?
    /** Task parameters */
    public var taskParameters: TaskParameters?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["filter"] = self.filter
        nillableDictionary["taskType"] = self.taskType
        nillableDictionary["dtid"] = self.dtid
        nillableDictionary["property"] = self.property
        nillableDictionary["dids"] = self.dids?.encodeToJSON()
        nillableDictionary["taskParameters"] = self.taskParameters?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
