//
// TaskByDid.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public class TaskByDid: JSONEncodable {
    /** Filter */
    public var filter: String?
    /** Task type */
    public var taskType: String?
    /** Modified on */
    public var modifiedOn: Int64?
    /** Device Type ID */
    public var dtid: String?
    /** Status counts */
    public var statusCounts: TaskStatusCounts?
    /** Property */
    public var property: String?
    /** Last known device task status for the specified did */
    public var statuses: [DeviceTask]?
    /** Task ID */
    public var id: String?
    /** Device IDs */
    public var dids: [String]?
    /** Task parameters */
    public var taskParameters: TaskParameters?
    /** Created on */
    public var createdOn: Int64?
    /** Status */
    public var status: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["filter"] = self.filter
        nillableDictionary["taskType"] = self.taskType
        nillableDictionary["modifiedOn"] = self.modifiedOn?.encodeToJSON()
        nillableDictionary["dtid"] = self.dtid
        nillableDictionary["statusCounts"] = self.statusCounts?.encodeToJSON()
        nillableDictionary["property"] = self.property
        nillableDictionary["statuses"] = self.statuses?.encodeToJSON()
        nillableDictionary["id"] = self.id
        nillableDictionary["dids"] = self.dids?.encodeToJSON()
        nillableDictionary["taskParameters"] = self.taskParameters?.encodeToJSON()
        nillableDictionary["createdOn"] = self.createdOn?.encodeToJSON()
        nillableDictionary["status"] = self.status
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
