//
// TaskListEnvelope.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public class TaskListEnvelope: JSONEncodable {
    /** Total */
    public var total: Int32?
    /** Envelope for task list */
    public var data: TaskList?
    /** Status counts */
    public var statusCounts: TasksStatusCounts?
    /** Offset */
    public var offset: Int32?
    /** Count */
    public var count: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["total"] = self.total?.encodeToJSON()
        nillableDictionary["data"] = self.data?.encodeToJSON()
        nillableDictionary["statusCounts"] = self.statusCounts?.encodeToJSON()
        nillableDictionary["offset"] = self.offset?.encodeToJSON()
        nillableDictionary["count"] = self.count?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
