//
// TasksStatusCounts.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public class TasksStatusCounts: JSONEncodable {
    /** Cancelled */
    public var CANCELLED: Int32?
    /** Complete */
    public var COMPLETE: Int32?
    /** Processing */
    public var PROCESSING: Int32?
    /** Requested */
    public var REQUESTED: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["CANCELLED"] = self.CANCELLED?.encodeToJSON()
        nillableDictionary["COMPLETE"] = self.COMPLETE?.encodeToJSON()
        nillableDictionary["PROCESSING"] = self.PROCESSING?.encodeToJSON()
        nillableDictionary["REQUESTED"] = self.REQUESTED?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
