//
// TaskByDidListEnvelope.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public class TaskByDidListEnvelope: JSONEncodable {
    /** Total number of tasks in list */
    public var total: Int32?
    /** Device task list envelope */
    public var data: TaskByDidList?
    /** Offset if using pagination */
    public var offset: Int32?
    /** Count for current result set */
    public var count: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["total"] = self.total?.encodeToJSON()
        nillableDictionary["data"] = self.data?.encodeToJSON()
        nillableDictionary["offset"] = self.offset?.encodeToJSON()
        nillableDictionary["count"] = self.count?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
