//
// TaskStatusCounts.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public class TaskStatusCounts: JSONEncodable {
    /** Number failed */
    public var numFailed: Int32?
    /** Number cancelled */
    public var numCancelled: Int32?
    /** Total devices */
    public var totalDevices: Int32?
    /** Number completed */
    public var numCompleted: Int32?
    /** Number succeeded */
    public var numSucceeded: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["numFailed"] = self.numFailed?.encodeToJSON()
        nillableDictionary["numCancelled"] = self.numCancelled?.encodeToJSON()
        nillableDictionary["totalDevices"] = self.totalDevices?.encodeToJSON()
        nillableDictionary["numCompleted"] = self.numCompleted?.encodeToJSON()
        nillableDictionary["numSucceeded"] = self.numSucceeded?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
